name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: '1.26'
    - name: Install dependencies
      run: go mod tidy
    - name: Test
      run: make test

   # Requires root privileges and Linux kernel/IPVS access.
   # Not supported on standard GitHub-hosted runners.
   # - name: Test E2E
   #   run: sudo make test-e2e